physical:
  name: N

# pre_training:
#   use: False

model:
  name: 1e
  # name: jcb
  # name: nc
  # name: jcbnc
  # name: dpe4

  jcb:
    n_channels: 4

  nonlinear_coupling:
    softmax_w: True
    activation: tanh

  # orbitals:
  #   n_determinants: 32

logging:
  wandb:
    entity: szke
    project: DPE

experiment_name: dev
