physical:
  name: N

model:
  name: dpe4

logging:
  wandb:
    entity: szke
    project: DPE

optimization:
  n_epochs: 60000
  intermediate_eval:
    opt_epochs: [20000, 40000]
    n_epochs: 10000

experiment_name: baseline
